# Generated by Django 5.2.14 on 2026-06-16 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_profiles_for_existing_users'),
        ('orders', '0009_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.city', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.neighborhood', verbose_name='Bairro'),
        ),
    ]
