# Generated by Django 5.2.14 on 2026-07-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32, verbose_name='Ação')),
                ('key', models.CharField(max_length=128, verbose_name='Chave (IP/identificador)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
            ],
            options={
                'verbose_name': 'tentativa de acesso',
                'verbose_name_plural': 'tentativas de acesso',
                'indexes': [models.Index(fields=['scope', 'key', 'created_at'], name='access_attempt_lookup_idx')],
            },
        ),
    ]
