# Generated by Django 5.2.14 on 2026-06-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_image_menuitem_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time_max',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo máximo de entrega, em minutos.', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time_min',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo mínimo de entrega, em minutos.', null=True),
        ),
    ]
