# Generated by Django 5.2.14 on 2026-07-01 01:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_restaurant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('selection_type', models.CharField(choices=[('single', 'Escolha única'), ('multiple', 'Múltipla escolha')], default='single', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_groups', to='menu.restaurant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplementChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='menu.complementgroup')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='complement_groups',
            field=models.ManyToManyField(blank=True, related_name='items', to='menu.complementgroup'),
        ),
    ]
