# Generated by Django 5.2.14 on 2026-07-01 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_migrate_complements_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoptiongroup',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='ItemOptionChoice',
        ),
        migrations.DeleteModel(
            name='ItemOptionGroup',
        ),
    ]
