# Generated by Django 5.2.14 on 2026-07-23 02:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_legacy_option_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='free_delivery_above',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acima deste valor em itens a taxa de entrega é zerada. Vazio = sempre cobra.', max_digits=8, null=True, verbose_name='Entrega grátis a partir de'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='minimum_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor mínimo dos itens para pedidos com entrega. 0 = sem mínimo.', max_digits=8, verbose_name='Pedido mínimo'),
        ),
    ]
