# Generated by Django 5.2.14 on 2026-10-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_restaurant_free_delivery_above_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accepting_orders',
            field=models.BooleanField(default=True, verbose_name='Receber pedidos agora'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de atendimento e privacidade'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razão social / responsável'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='CNPJ / identificação do responsável'),
        ),
    ]
