# Generated by Django 5.2.14 on 2026-06-06 03:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120)),
                ('choice_name', models.CharField(max_length=120)),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orders.orderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
