# Generated by Django 5.2.14 on 2026-06-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_method',
            field=models.CharField(choices=[('delivery', 'Entrega'), ('pickup', 'Retirada')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('card_on_delivery', 'Cartão na entrega'), ('pix', 'PIX')], default='cash', max_length=30),
        ),
    ]
