# Generated by Django 5.2.14 on 2026-06-09 03:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address_cep_order_address_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cidade')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Taxa de entrega')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_cep',
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bairro')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Taxa de entrega')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='orders.city', verbose_name='cidade')),
            ],
            options={
                'verbose_name': 'bairro',
                'verbose_name_plural': 'bairros',
                'ordering': ['name'],
                'unique_together': {('city', 'name')},
            },
        ),
    ]
