# Generated by Django 5.2.14 on 2026-06-10 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_city_remove_order_address_cep_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status do pagamento'),
        ),
        migrations.CreateModel(
            name='PixPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('external_reference', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code_text', models.TextField(blank=True)),
                ('qr_code_base64', models.TextField(blank=True)),
                ('txid', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix_payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'pagamento Pix',
                'verbose_name_plural': 'pagamentos Pix',
                'ordering': ['-created_at'],
            },
        ),
    ]
