# Generated by Django 5.2.14 on 2026-06-10 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_customer_cpf_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('card_on_delivery', 'Cartão na entrega'), ('credit_card', 'Cartão de crédito'), ('pix', 'PIX')], default='cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_process', 'Em análise'), ('paid', 'Pago'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status do pagamento'),
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('external_reference', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('in_process', 'Em análise'), ('pending', 'Pendente'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado')], default='pending', max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments', models.PositiveIntegerField(default=1)),
                ('payment_method_id', models.CharField(blank=True, max_length=40)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'pagamento com cartão',
                'verbose_name_plural': 'pagamentos com cartão',
                'ordering': ['-created_at'],
            },
        ),
    ]
