# Generated by Django 5.2.14 on 2026-06-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Recebido'), ('preparing', 'Em preparo'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='received', max_length=30),
        ),
    ]
