# Generated by Django 5.2.14 on 2026-10-07 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_order_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cardpayment',
            name='status',
            field=models.CharField(choices=[('approved', 'Aprovado'), ('in_process', 'Em análise'), ('pending', 'Pendente'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado'), ('charged_back', 'Contestado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_process', 'Em análise'), ('paid', 'Pago'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado'), ('charged_back', 'Contestado')], default='pending', max_length=20, verbose_name='Status do pagamento'),
        ),
        migrations.AlterField(
            model_name='pixpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('refunded', 'Estornado'), ('charged_back', 'Contestado')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('card_on_delivery', 'Cartão na entrega'), ('credit_card', 'Cartão de crédito'), ('pix', 'PIX')], max_length=30)),
                ('fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
                ('external_reference', models.CharField(editable=False, max_length=64, unique=True)),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('creating', 'Solicitando pagamento'), ('uncertain', 'Verificando pagamento'), ('pending', 'Pendente'), ('in_process', 'Em análise'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('refunded', 'Estornado'), ('charged_back', 'Contestado'), ('failed', 'Não iniciado')], default='creating', max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='attempt_status_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fingerprint', ''), _negated=True), fields=('order', 'method', 'fingerprint'), name='unique_payment_fingerprint'), models.UniqueConstraint(condition=models.Q(('mp_payment_id', ''), _negated=True), fields=('mp_payment_id',), name='unique_attempt_mp_id')],
            },
        ),
    ]
