# Generated by Django 5.2.14 on 2026-10-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_checkout_key_alter_cardpayment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('refund_payment', 'Pode estornar pagamentos online')]},
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
