# Generated by Django 5.2.14 on 2026-10-07 02:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=120, unique=True)),
                ('order_status', models.CharField(choices=[('received', 'Recebido'), ('preparing', 'Em preparo'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Aguardando envio'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou'), ('uncertain', 'Verificando envio'), ('skipped', 'Não enviada')], default='pending', max_length=20)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='whatsapp_pending_idx')],
            },
        ),
    ]
