# Generated by Django 5.2.14 on 2026-10-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_whatsapp_opt_in_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
