# Generated by Django 5.2.14 on 2026-10-07 10:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_paymentattempt_last_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='requested_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_process', 'Em análise'), ('paid', 'Pago'), ('partially_refunded', 'Estornado parcialmente'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado'), ('charged_back', 'Contestado')], default='pending', max_length=20, verbose_name='Status do pagamento'),
        ),
    ]
